/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Categorys {
  id: Generated<number>;
  name: string;
}

export interface Classes {
  id: Generated<number>;
  name: string;
}

export interface Finances {
  category: number;
  class: number;
  expenditure: Decimal | null;
  id: Generated<number>;
  income: Decimal | null;
  month: number;
  name: string;
  user: number;
  year: number;
}

export interface Tokens {
  id: Generated<number>;
  token: string;
  user: number;
}

export interface Users {
  confirmed: Generated<number | null>;
  email: string;
  id: Generated<number>;
  lastname: string | null;
  name: string;
  password: string;
}

export interface DB {
  categorys: Categorys;
  classes: Classes;
  finances: Finances;
  tokens: Tokens;
  users: Users;
}
