/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Categorys {
  id: string;
  name: string;
  user: string;
}

export interface Finances {
  category: string;
  class: "expenditure" | "income";
  expenditure: Generated<Decimal | null>;
  id: string;
  income: Generated<Decimal | null>;
  month: number;
  name: string;
  user: string;
  year: number;
}

export interface Tokens {
  id: string;
  token: string;
  user: string;
}

export interface Users {
  confirmed: Generated<number | null>;
  email: string;
  id: string;
  lastname: string | null;
  name: string;
  password: string;
}

export interface DB {
  categorys: Categorys;
  finances: Finances;
  tokens: Tokens;
  users: Users;
}
